services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=flick
      - POSTGRES_USER=flick
      - POSTGRES_PASSWORD=pqlamz!!
      - TZ=Asia/Seoul
      - PGTZ=Asia/Seoul
    networks:
      - flick_network
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    networks:
      - flick_network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - flick_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  service-registry:
    image: jbj338033/flick-service-registry:latest
    container_name: service-registry
    networks:
      - flick_network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  notification-service:
    image: jbj338033/flick-notification-service:latest
    container_name: notification-service
    networks:
      - flick_network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  core-service:
    image: jbj338033/flick-core-service:latest
    container_name: core-service
    networks:
      - flick_network
    ports:
      - 8081:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
      - kafka
      - service-registry

  place-service:
    image: jbj338033/flick-place-service:latest
    container_name: place-service
    networks:
      - flick_network
    ports:
      - 8082:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
      - kafka
      - place-redis
      - service-registry

  place-redis:
    image: redis:latest
    container_name: place-redis
    networks:
      - flick_network

  admin-service:
    image: jbj338033/flick-admin-service:latest
    container_name: admin-service
    networks:
      - flick_network
    ports:
      - 8083:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
      - kafka
      - service-registry

volumes:
  postgres_data:

networks:
  flick_network:
    driver: bridge
